name: Lint Frontend

on: [push, pull_request]

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    name: Lint HTML, CSS, and JS
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install linters and configuration
        run: |
          # Install the main linters globally
          npm install -g htmlhint stylelint eslint
          
          # Install the specific configuration Stylelint needs globally
          npm install -g stylelint-config-standard
          
          # Install the standard ruleset for ESLint (v9+) globally
          npm install -g @eslint/js

          # This resolves the "Cannot find module 'globals'" error.
          npm install -g globals

      - name: Create Configuration Files
        run: |
          # 1. Create Stylelint Config (as done previously)
          echo '{"extends": ["stylelint-config-standard"]}' > .stylelintrc.json
          
          # 2. Create ESLint Config (required for v9+)
          # This config tells ESLint to use the standard recommended rules.
          echo "const globals = require('globals');
            module.exports = [
            {
                files: ['**/*.js'],
                languageOptions: {
                ecmaVersion: 2021,
                sourceType: 'module',
                globals: {
                ...globals.browser,
                ...globals.node,
                },
                },
            rules: {
                // Add your desired ESLint rules here
                'semi': ['error', 'always'],
                'prefer-const': 'error',
                },
            },
            ];" > eslint.config.js

      - name: Lint HTML
        run: htmlhint app/src/main/resources/static/pages//*.html || true

      - name: Lint CSS
        run: stylelint app/src/main/resources/static/assets/css//*.css || true

      - name: Lint JS
        run: eslint app/src/main/resources/static/js//*.js || true