name: Lint Frontend

on: [push, pull_request]

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    name: Lint HTML, CSS, and JS
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install linters and configuration
        run: |
          # Install the main linters globally
          npm install -g htmlhint stylelint eslint
          
          # Install the specific configuration Stylelint needs globally
          # This resolves the "ConfigurationError: No configuration provided"
          npm install -g stylelint-config-standard

      - name: Create Stylelint Configuration File
        # Use an inline shell command to create the necessary config file
        run: |
          echo '{"extends": ["stylelint-config-standard"]}' > .stylelintrc.json

      - name: Lint HTML
        run: htmlhint app/src/main/resources/static/pages//*.html || true

      - name: Lint CSS
        run: stylelint app/src/main/resources/static/assets/css//*.css || true

      - name: Lint JS
        run: eslint app/src/main/resources/static/js//*.js || true